spring:
  datasource:
    url: jdbc:mysql://charmitshard.c9si8s82idtr.ap-northeast-2.rds.amazonaws.com:3306/charmitshard?serverTimezone=Asia/Seoul
    username: admin
    password: clftkadl7&
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8080
